### ISSUE TITLE
Allow adding holes with same orientation as base face

### ISSUE THREAD

**Issue by macumber** [automaticmagic/topolys#11]
Taking the opportunity for a suggestion. As it stands, Topolys requires that parent applications/wrappers (e.g. TBD) send (as input) holes with wire normals inverted with respect to their parent face. IMO, if a parent application "gets" (i.e. creates) a Topolys face with "holes" (i.e. an array of wires) as input (i.e. the intention is clear enough), Topolys should be able to evaluate if such holes are inverted or not, and invert those that aren't. This looks like internal logic to Topolys, and therefore such functionality (e.g. evaluation, inversion) should - in my opinion - reside within Topolys code. The operation is simple enough (.reverse).

**Comment by rd2** [comment]
A possible prerequisite: there's a need to better understand the role of Topolys "holes". Strictly there to accommodate subsurfaces? Or maybe also rare cases such interior [courtyards](https://www.curbed.com/2018/2/23/17043812/courtyard-house-modern-architecture-australia) (as seen from above), with a single roof surface encompassing all 4x sides of the courtyard? In small-scale residential, it may be plausible to have a single roof surface encompassing all 4x sides of a courtyard, but doubtful for anything larger (the roof surface would usually be broken up into multiple, non-holed surfaces as a function of spatial zoning). So I can appreciate the usefulness of "holes" for the courtyard cases. Yet If only there to accommodate subsurfaces, maybe holes should be entirely internal to Topolys, as it should - ideally - detect (internally) surface overlaps, surfaces eclipsing other surfaces (100% glazed walls), surfaces "holding" other surfaces without edge collision (more traditional punched windows), and so on. That's something to consider in the future.

**Comment by macumber** [comment]
Changed convention so holes are same winding as faces, this is more convenient for OpenStudio.  Can open a new issue if we need to support reverse winding.
