### ISSUE TITLE
floating point imprecision when calling acos in Vector3D "angle" method

### ISSUE THREAD

**Issue by rd2** [automaticmagic/topolys#14]
Came across cases in testing where the Topolys::Vector3d "angle" method will fail because of floating point imprecision with the Math.acos function. Input domain is restricted to (-1, 1), but in some rare cases one gets 1.0000000000000002. This is a know [issue](http://www.jsylvest.com/blog/tag/programming/), and the solution is straightforward:

`val = [-1.0, val].max`
`val = [ val, 1.0].min`
`psi = acos(val)`

... working around this in TBD for now, but will PR a fix soonish.

**Comment by macumber** [comment]
Thanks for finding this!

**Comment by macumber** [comment]
I made this PR, hope it isn't stepping on your changes too much
