### ISSUE TITLE
RubyGems redirects to missing GitHub repo

### ISSUE THREAD

**Issue by brgix** [automaticmagic/topolys#25]
@macumber: _gemspec_ entries [here](https://github.com/automaticmagic/topolys/blob/f4e4b95b78933e4cff6801ab91d782476d353277/topolys.gemspec#L14) and [here](https://github.com/automaticmagic/topolys/blob/f4e4b95b78933e4cff6801ab91d782476d353277/topolys.gemspec#L24) reference what is most likely the initial GitHub repo URL (should be `/automaticmagic/` - not `/macumber/`). Hadn't noticed before. The issue popped up when clicking on some of the RubyGems [links](https://rubygems.org/gems/topolys) - invalid URLs (404s). Easy fixes, maybe for next release?

**Comment by macumber** [comment]
Doh!  Fixed, thank you!
